apiVersion: v2
name: jdownloader2
description: jDownloader2 Helm chart for Kubernetes. "JDownloader is a free, open-source download management tool with a huge community that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!"

type: application

version: 0.2.0
appVersion: "v23.03.1"

home: https://jdownloader.org/
sources:
  - https://jdownloader.org/

icon: https://github.com/pmoscode/jdownloader2/raw/main/assets/logo.png

maintainers:
  - name: pmoscode
    email: info@pmoscode.de
    url: https://pmoscode.de

annotations:
  artifacthub.io/images: |
    - name: jdownloader2
      image: jlesage/jdownloader-2:v23.03.1
      platforms:
        - linux/amd64
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/pmoscode-helm/jdownloader2
    - name: support
      url: https://github.com/pmoscode-helm/jdownloader2/issues
  artifacthub.io/maintainers: |
    - name: pmoscode
      email: info@pmoscode.de
