apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jdownloader2-headless.fullname" . }}
  labels:
    {{- include "jdownloader2-headless.labels" . | nindent 4 }}
spec:
  {{- if .Values.strategy }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "jdownloader2-headless.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jdownloader2-headless.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jdownloader2-headless.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.myjd.enabled }}
          env:
            - name: MYJDOWNLOADER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: email
                  name: {{ include "jdownloader2-headless.secretName" . }}
            - name: MYJDOWNLOADER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "jdownloader2-headless.secretName" . }}
            - name: MYJDOWNLOADER_DEVICE_NAME
              value: {{ include "jdownloader2-headless.fullname" . }}-id
          {{- end }}
          volumeMounts:
            - name: {{ include "jdownloader2-headless.fullname" . }}-data
              subPath: config
              mountPath: /config
            - name: {{ include "jdownloader2-headless.fullname" . }}-data
              subPath: downloads
              mountPath: /output
        {{- if .Values.additionalVolumeMounts }}
        {{- toYaml .Values.additionalVolumeMounts | nindent 12  }}
        {{- end }}
          ports:
            {{- if .Values.service.myjd.enabled }}
            - name: myjd
              containerPort: {{ .Values.service.myjd.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.vnc.enabled }}
            - name: vnc
              containerPort: 5900
              protocol: TCP
            {{- end }}
            - name: web
              containerPort: 5800
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
          readinessProbe:
            httpGet:
              path: /
              port: web
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "jdownloader2-headless.fullname" . }}-data
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
          persistentVolumeClaim:
            claimName: {{ include "jdownloader2-headless.fullname" . }}-data
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8  }}
        {{- end }}
