{{- if and .Values.service.myjd.enabled (eq .Values.myjd.existingSecretName "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jdownloader2-headless.fullname" . }}-secret
type: Opaque
data:
  email: {{ .Values.myjd.email | b64enc }}
  password: {{ .Values.myjd.password | b64enc }}
{{- end }}
